# ref. https://goreleaser.com/customization/build/
builds:
  - id: camino-network-runner
    main: ./main.go
    binary: camino-network-runner
    flags:
      - -v
    ldflags:
      - -X 'github.com/ava-labs/avalanche-network-runner/cmd.Version={{.Version}}'
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - darwin_arm64
    overrides:
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: chain4travel
    name: camino-network-runner
