name: Build + Test + Release

on:
  push:
    branches:
      - chain4travel
  pull_request:
  release:
      types: [created]

permissions:
  contents: write

jobs:
  lint_test:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - name: Allow access to camino-operator repo
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CAMBOT_PAT }}
        run: git config --global url."https://${GITHUB_ACCESS_TOKEN}@github.com/chain4travel/camino-operator".insteadOf "https://github.com/chain4travel/camino-operator"
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: "v1.45"
          working-directory: .
          args: --timeout 3m
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    concurrency: node_fence
    steps:
      - name: Allow access to camino-operator repo
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CAMBOT_PAT }}
        run: git config --global url."https://${GITHUB_ACCESS_TOKEN}@github.com/chain4travel/camino-operator".insteadOf "https://github.com/chain4travel/camino-operator"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2" # The Go version to use.
      - run: go test -v -timeout 10m -race ./...
  #e2e_test:
  #  name: e2e tests
  #  runs-on: ubuntu-latest
  #  concurrency: node_fence
  #  steps:
  #    - name: Git checkout
  #      uses: actions/checkout@v2
  #      with:
  #        fetch-depth: 0
  #    - name: Set up Go
  #      uses: actions/setup-go@v2
  #      with:
  #        go-version: 1.17
  #    - name: Run e2e tests
  #      shell: bash
  #      run: scripts/tests.e2e.sh 0.1.0 0.1.0
  release:
    #needs: [lint_test, unit_test, e2e_test]
    needs: [lint_test, unit_test]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
