name: Build + Test + Release

on:
  push:
    branches:
      - chain4travel
  pull_request:
  release:
      types: [created]

permissions:
  contents: write

jobs:
  lint_test:
    name: Lint tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: "v1.47.0"
          working-directory: .
          args: --timeout 3m
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    concurrency: node_fence
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test -v -timeout 10m -race ./...
        env:
          CGO_CFLAGS: "-O -D__BLST_PORTABLE__" # Set the CGO flags to use the portable version of BLST
  e2e_test:
    name: e2e tests
    runs-on: ubuntu-latest
    concurrency: node_fence
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run e2e tests
        shell: bash
        run: scripts/tests.e2e.sh 0.3.0-alpha1 0.3.0-alpha1
  release:
    needs: [lint_test, unit_test]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: camino-network-runner
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Set up arm64 cross compiler
        run: sudo apt-get -y install gcc-aarch64-linux-gnu
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./camino-network-runner/
        env:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
